project:
  type: website
  output-dir: docs

website:
  title: "JerryLuuuu's personal website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: cv-acadmic-Yen-Chia_Lu(Jerry).pdf
        text: CV
        

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true


